version: '3.8'

services:
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - 8500:8500

  database:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 9000:8080
    links:
      - database:db
